apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-331-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.org/websocket-services: "ws"
    nginx.ingress.kubernetes.io/limit-connections: "100"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-rpm: "500"
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: headless-lms
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cms
                port:
                  number: 3000
