name: Build and deploy headless-lms docs

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and build
        run: cargo doc
        working-directory: headless-lms

      - name: Copy index to target/doc
        run: cp doc_index.html target/doc/index.html
        working-directory: headless-lms

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: headless-lms/target/doc
